# .pre-commit-config.yaml
repos:
  # 使用 pre-commit 官方提供的常用 hook 工具集
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-merge-conflict

  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix"]

  # JavaScript / TypeScript - 限制只格式化 JS/TS，避免 HTML 衝突
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|json|yaml|yml)$
        exclude: \.(html|md)$
